project_id = "tf-lab"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://localhost:5173"]
enable_signup = false
minimum_password_length = 12

[storage]
enabled = true
file_size_limit = "8MiB"
